version: "3"

services:
  ehealthkd:
    image: "jpconsuegra/ehealthkd-2020"
    build: "."
    volumes:
      - "./:/workspace"
      - "./kdtools/kdtools:/usr/local/lib/python3.8/site-packages/kdtools"
      - "~/.ssh/id_rsa:/root/.ssh/id_rsa"
    network_mode: "host"